version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout  # Clone the repository

      - run:
          name: Install dependencies
          command: |  # Install dependencies efficiently
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Linting with Flake8
          command: |
            python -m flake8  # Check code style
      - run:
          name: Run tests
          command: |
            python -m pytest tests/  # Execute tests

      - setup_remote_docker  # Configure for remote Docker (if needed)

      - run:
          name: Build Docker image
          command: |
            docker build -t prakashpatildevinfo/app .

      - run:
          name: Push Docker image to DockerHub
          command: |
            docker login -u prakashpatildevinfo -p dckr_pat_9ZhCHHhjd9_AW3482Y9ezrpYVJY
            docker tag app prakashpatildevinfo/app
            docker push prakashpatildevinfo/app

workflows:
  build_and_test:
    jobs:
      - build
