version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      # - run:
      #     name: Update Debian package repositories
      #     command: |
      #       sudo sed -i '/stretch-updates/d' /etc/apt/sources.list
      #       sudo sed -i '/stretch/d' /etc/apt/sources.list
      #       sudo apt-get update
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Linting with Flake8
          command: |
            python -m flake8
      - run:
          name: Run tests
          command: |
            python -m pytest tests/

      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t app .
      - run:
          name: Push Docker image to DockerHub
          command: |
            docker login -u prakashpatildevinfo -p dckr_pat_9ZhCHHhjd9_AW3482Y9ezrpYVJY
            docker tag app prakashpatildevinfo/app
            docker push prakashpatildevinfo/app


workflows:
  version: 2
  build_and_test:
    jobs:
      - build